import { useState } from "react";
import { ArrowDown, ArrowUp, Copy, Gauge, Group, Pencil, Plus, Trash2 } from "lucide-react";
import type { GroupType, MihomoConfig, ProxyGroup } from "../../shared/types";
import { ConfirmDialog, Drawer } from "../Dialog";

const groupTypes: { value: GroupType; label: string }[] = [{ value: "select", label: "手动选择" }, { value: "url-test", label: "自动测速" }, { value: "fallback", label: "故障转移" }, { value: "load-balance", label: "负载均衡" }, { value: "relay", label: "链式代理" }];
const blankGroup = (): ProxyGroup => ({ id: crypto.randomUUID(), name: "新策略组", type: "select", proxies: ["DIRECT"], extra: {} });

export function GroupsView({ config, onChange }: { config: MihomoConfig; onChange: (config: MihomoConfig) => void }) {
  const [editing, setEditing] = useState<ProxyGroup | null>(null);
  const [deleting, setDeleting] = useState<ProxyGroup | null>(null);
  const save = (group: ProxyGroup) => { const exists = config.proxyGroups.some((item) => item.id === group.id); onChange({ ...config, proxyGroups: exists ? config.proxyGroups.map((item) => item.id === group.id ? group : item) : [...config.proxyGroups, group] }); setEditing(null); };
  const move = (group: ProxyGroup, direction: -1 | 1) => { const index = config.proxyGroups.findIndex((item) => item.id === group.id); const target = index + direction; if (target < 0 || target >= config.proxyGroups.length) return; const next = [...config.proxyGroups]; [next[index], next[target]] = [next[target], next[index]]; onChange({ ...config, proxyGroups: next }); };
  return <>
    <div className="view-toolbar"><div className="summary-inline"><span><strong>{config.proxyGroups.length}</strong> 个策略组</span><i /><span><strong>{config.proxyGroups.reduce((sum, item) => sum + item.proxies.length, 0)}</strong> 个成员引用</span></div><button className="primary-button" onClick={() => setEditing(blankGroup())}><Plus size={17} />添加策略组</button></div>
    {config.proxyGroups.length ? <div className="group-list">{config.proxyGroups.map((group) => <article className="group-card" key={group.id}><div className="group-card-main"><span className="group-icon">{group.type === "url-test" ? <Gauge size={20} /> : <Group size={20} />}</span><div><h2>{group.name}</h2><span>{groupTypes.find((item) => item.value === group.type)?.label || group.type}</span></div><b>{group.proxies.length}</b></div><div className="member-preview">{group.proxies.slice(0, 5).map((member) => <span key={member}>{member}</span>)}{group.proxies.length > 5 && <span>+{group.proxies.length - 5}</span>}</div><div className="group-actions"><button className="icon-button compact" onClick={() => move(group, -1)} aria-label={`上移 ${group.name}`}><ArrowUp size={16} /></button><button className="icon-button compact" onClick={() => move(group, 1)} aria-label={`下移 ${group.name}`}><ArrowDown size={16} /></button><button className="secondary-button compact-button" onClick={() => save({ ...group, id: crypto.randomUUID(), name: `${group.name} 副本` })}><Copy size={15} />复制</button><button className="secondary-button compact-button" onClick={() => setEditing(structuredClone(group))}><Pencil size={15} />编辑</button><button className="icon-button compact danger" onClick={() => setDeleting(group)} aria-label={`删除 ${group.name}`}><Trash2 size={16} /></button></div></article>)}</div> : <div className="empty-state"><div><Group size={24} /></div><h2>还没有策略组</h2><button className="primary-button" onClick={() => setEditing(blankGroup())}><Plus size={17} />添加策略组</button></div>}
    <GroupEditor key={editing?.id || "closed"} config={config} group={editing} onClose={() => setEditing(null)} onSave={save} />
    <ConfirmDialog open={!!deleting} title="删除策略组" message={`确定删除“${deleting?.name}”吗？引用该组的规则会变为无效。`} onClose={() => setDeleting(null)} onConfirm={() => { if (deleting) onChange({ ...config, proxyGroups: config.proxyGroups.filter((item) => item.id !== deleting.id) }); setDeleting(null); }} />
  </>;
}

function GroupEditor({ config, group, onClose, onSave }: { config: MihomoConfig; group: ProxyGroup | null; onClose: () => void; onSave: (group: ProxyGroup) => void }) {
  const [draft, setDraft] = useState<ProxyGroup | null>(group);
  if (!group || !draft) return null;
  const memberOptions = ["DIRECT", "REJECT", ...config.proxies.map((item) => item.name), ...config.proxyGroups.filter((item) => item.id !== draft.id).map((item) => item.name)];
  const toggleMember = (member: string) => setDraft({ ...draft, proxies: draft.proxies.includes(member) ? draft.proxies.filter((item) => item !== member) : [...draft.proxies, member] });
  const moveMember = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= draft.proxies.length) return; const proxies = [...draft.proxies]; [proxies[index], proxies[target]] = [proxies[target], proxies[index]]; setDraft({ ...draft, proxies }); };
  return <Drawer title={group.name === "新策略组" ? "添加策略组" : `编辑 ${group.name}`} open onClose={onClose} footer={<><button className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" onClick={() => onSave(draft)}>保存策略组</button></>}>
    <div className="form-grid"><label className="span-2">策略组名称<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label className="span-2">类型<select value={draft.type} onChange={(e) => setDraft({ ...draft, type: e.target.value as GroupType })}>{groupTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{draft.type !== "select" && draft.type !== "relay" && <><label className="span-2">测速 URL<input value={draft.url || "https://www.gstatic.com/generate_204"} onChange={(e) => setDraft({ ...draft, url: e.target.value })} /></label><label>间隔（秒）<input type="number" min={10} value={draft.interval || 300} onChange={(e) => setDraft({ ...draft, interval: Number(e.target.value) })} /></label><label>容差（毫秒）<input type="number" min={0} value={draft.tolerance || 50} onChange={(e) => setDraft({ ...draft, tolerance: Number(e.target.value) })} /></label></>}</div>
    <fieldset className="member-selector"><legend>成员</legend><div className="member-options">{memberOptions.map((member) => <label key={member}><input type="checkbox" checked={draft.proxies.includes(member)} onChange={() => toggleMember(member)} /><span>{member}</span></label>)}</div></fieldset>
    {!!draft.proxies.length && <div className="ordered-members"><strong>当前顺序</strong>{draft.proxies.map((member, index) => <div key={`${member}-${index}`}><span className="order-number">{index + 1}</span><span>{member}</span><button className="icon-button compact" onClick={() => moveMember(index, -1)} aria-label={`上移 ${member}`}><ArrowUp size={15} /></button><button className="icon-button compact" onClick={() => moveMember(index, 1)} aria-label={`下移 ${member}`}><ArrowDown size={15} /></button></div>)}</div>}
  </Drawer>;
}
