import type { MihomoConfig, Project } from "../../shared/types";

export function SettingsView({ project, onChange }: { project: Project; onChange: (updater: (current: Project) => Project) => void }) {
  const updateConfig = <K extends keyof MihomoConfig>(key: K, value: MihomoConfig[K]) => onChange((current) => ({ ...current, config: { ...current.config, [key]: value } }));
  return <div className="settings-layout">
    <section className="settings-section"><header><h2>项目</h2></header><div className="settings-form"><label>配置名称<input value={project.name} onChange={(e) => onChange((current) => ({ ...current, name: e.target.value }))} /></label></div></section>
    <section className="settings-section"><header><h2>运行参数</h2></header><div className="settings-form two-columns"><label>混合端口<input type="number" min={1} max={65535} value={project.config.mixedPort} onChange={(e) => updateConfig("mixedPort", Number(e.target.value))} /></label><label>运行模式<select value={project.config.mode} onChange={(e) => updateConfig("mode", e.target.value as MihomoConfig["mode"])}><option value="rule">规则</option><option value="global">全局</option><option value="direct">直连</option></select></label><label>日志级别<select value={project.config.logLevel} onChange={(e) => updateConfig("logLevel", e.target.value as MihomoConfig["logLevel"])}><option value="silent">静默</option><option value="error">错误</option><option value="warning">警告</option><option value="info">信息</option><option value="debug">调试</option></select></label><label>外部控制器<input value={project.config.externalController} onChange={(e) => updateConfig("externalController", e.target.value)} /></label></div></section>
    <section className="settings-section"><header><h2>网络</h2></header><div className="toggle-stack"><label className="toggle-row"><span><strong>允许局域网连接</strong><small>allow-lan</small></span><input type="checkbox" checked={project.config.allowLan} onChange={(e) => updateConfig("allowLan", e.target.checked)} /></label><label className="toggle-row"><span><strong>启用 IPv6</strong><small>ipv6</small></span><input type="checkbox" checked={project.config.ipv6} onChange={(e) => updateConfig("ipv6", e.target.checked)} /></label></div></section>
  </div>;
}
