import { useEffect, useState } from "react";
import { CheckCircle2, FileUp, Link2, Pencil, Plus, RefreshCw, Rss, Trash2 } from "lucide-react";
import { api } from "../../api";
import type { NodeSource } from "../../shared/domain";
import { ConfirmDialog, Drawer } from "../Dialog";

const empty = { name: "我的订阅", kind: "remote-url" as NodeSource["kind"], url: "", format: "auto" as NodeSource["format"] };
export function SourceManagerView({ onMessage }: { onMessage: (message: string) => void }) {
  const [items, setItems] = useState<NodeSource[]>([]);
  const [draft, setDraft] = useState<(typeof empty & { id?: string }) | null>(null);
  const [deleting, setDeleting] = useState<NodeSource | null>(null);
  const [refreshing, setRefreshing] = useState<string | null>(null);
  const load = () => api.listNodeSources().then(setItems).catch(error => onMessage(error instanceof Error ? error.message : "来源加载失败"));
  useEffect(() => { load(); }, []);
  async function save() { if (!draft) return; try { const saved = draft.id ? await api.updateNodeSource(draft.id, draft) : await api.createNodeSource(draft); setItems(current => draft.id ? current.map(item => item.id === saved.id ? saved : item) : [saved, ...current]); setDraft(null); onMessage(draft.id ? "订阅来源已更新" : "订阅来源已保存"); } catch (error) { onMessage(error instanceof Error ? error.message : "来源保存失败"); } }
  async function refresh(item: NodeSource) { if (!item.url) return; setRefreshing(item.id); try { const result = await api.refreshNodeSource(item.id); setItems(current => current.map(value => value.id === result.source.id ? result.source : value)); onMessage(`已刷新 ${result.nodes.length} 个节点${result.warnings.length ? `，${result.warnings.length} 条警告` : ""}`); } catch (error) { onMessage(error instanceof Error ? error.message : "来源刷新失败"); await load(); } finally { setRefreshing(null); } }
  return <>
    <div className="view-toolbar"><div className="summary-inline"><span><strong>{items.length}</strong> 个来源</span><i/><span><strong>{items.reduce((sum, item) => sum + item.nodeCount, 0)}</strong> 个节点</span></div><div className="row-actions"><button className="secondary-button" onClick={load}><RefreshCw size={16}/>刷新</button><button className="primary-button" onClick={() => setDraft(empty)}><Plus size={17}/>添加来源</button></div></div>
    {items.length ? <div className="subscription-list">{items.map(item => <article className="subscription-row" key={item.id}><span className="subscription-icon"><Rss size={20}/></span><div className="subscription-main"><h2>{item.name}</h2><span>{item.url || "手动来源"}</span>{item.lastError && <small className="subscription-error-detail" title={item.lastError}>{item.lastError}</small>}</div><span className="type-badge">{item.format}</span><div className="subscription-stats"><strong>{item.nodeCount}</strong><span>节点</span></div><div className="subscription-status">{item.lastError ? <><Trash2 size={15}/><span>刷新失败</span></> : <><CheckCircle2 size={15}/><span>{item.enabled ? "已启用" : "已停用"}</span></>}</div><div className="row-actions"><button className="icon-button compact" disabled={!item.url || refreshing === item.id} onClick={() => void refresh(item)} aria-label={`刷新 ${item.name}`} title={item.url ? "刷新来源" : "手动来源无需刷新"}>{refreshing === item.id ? <RefreshCw className="spin" size={16}/> : <RefreshCw size={16}/>}</button><button className="icon-button compact" onClick={() => setDraft({ id: item.id, name: item.name, kind: item.kind, url: item.url || "", format: item.format as NodeSource["format"] })} aria-label="编辑来源"><Pencil size={16}/></button><button className="icon-button compact danger" onClick={() => setDeleting(item)} aria-label="删除来源"><Trash2 size={16}/></button></div></article>)}</div> : <div className="empty-state"><div><Link2 size={24}/></div><h2>还没有订阅来源</h2><p>添加一个远程 URL，或者先建立手动节点来源。</p><button className="primary-button" onClick={() => setDraft(empty)}><Plus size={17}/>添加来源</button></div>}
    <Drawer open={!!draft} onClose={() => setDraft(null)} title={draft?.id ? `编辑来源：${draft.name}` : "添加订阅来源"} footer={<><button className="secondary-button" onClick={() => setDraft(null)}>取消</button><button className="primary-button" disabled={!draft?.name.trim() || (draft.kind === "remote-url" && !draft.url?.trim())} onClick={save}>保存来源</button></>}><div className="form-grid"><label className="span-2">来源名称<input value={draft?.name || ""} onChange={event => setDraft(current => current ? {...current, name: event.target.value} : current)}/></label><label>来源类型<select value={draft?.kind || "remote-url"} onChange={event => setDraft(current => current ? {...current, kind: event.target.value as NodeSource["kind"]} : current)}><option value="remote-url">远程订阅</option><option value="file">配置文件</option><option value="share-links">分享链接</option><option value="manual">手动节点</option></select></label><label>格式<select value={draft?.format || "auto"} onChange={event => setDraft(current => current ? {...current, format: event.target.value as NodeSource["format"]} : current)}><option value="auto">自动识别</option><option value="links">分享链接</option><option value="mihomo">Mihomo YAML</option><option value="sing-box">sing-box JSON</option></select></label><label className="span-2">订阅 URL<input type="url" value={draft?.url || ""} onChange={event => setDraft(current => current ? {...current, url: event.target.value} : current)} placeholder="https://example.com/subscribe"/></label><div className="form-hint span-2"><FileUp size={16}/>来源创建后，可在节点池中查看与编排节点。</div></div></Drawer>
    <ConfirmDialog open={!!deleting} title="删除订阅来源" message={`确定删除“${deleting?.name}”吗？来源节点会保留在节点池中。`} onClose={() => setDeleting(null)} onConfirm={async () => { if (deleting) await api.deleteNodeSource(deleting.id); setItems(current => current.filter(item => item.id !== deleting?.id)); setDeleting(null); onMessage("来源已删除"); }}/>
  </>;
}
